Do not try to convert already absolute path in uri_string:recompose/1
erlang/otp pull request #2795
Opened 2020-10-11 20:09 UTC by robertoaloi

According to the documentation, the `path` passed to `uri_string:recompose/1` via the `uri_map/0` is of type `unicode:chardata()`. From what I understand, a `path` expressed as `[<<"/">>, <<"tmp">>]` should be valid input, but that would be considered a relative path and therefore an extra slash would be prepended.

2020-10-11 20:32 UTC, essen commented
Don't know if code or doc is at fault here, but if it's the code then this fix is only partial, it won't work for `[<<"/t">>, <<"mp">>]`, or even for `["/", <<"tmp">>]` and any other `unicode:charlist` variant. Might be simpler to convert to list/binary before calling `make_path_absolute`.

2020-10-12 07:59 UTC, peterdmv requested changes
I agree with @essen, it is simpler to convert a possibly deep list to a list or binary. That change would handle all the special cases:
```erlang
1> unicode:characters_to_binary(["/", <<"tmp">>]).
<<"/tmp">>
2> unicode:characters_to_list([<<"/t">>, <<"mp">>]).  
"/tmp"
```
As this a bug, can you please base this PR on maint and provide testcases?

2020-10-12 08:50 UTC, robertoaloi commented
@essen Indeed. If we agree the code should support `unicode:charlist/0` (and that the documentation is correct), then your suggestion makes sense. I wonder if there's already a function in OTP which converts relative to absolute.
@peterdmv Yes, that are also needed.

@peterdmv I won't be able to work on this for the next couple of days, so feel free to jump on it. Otherwise I will try to provide a proper solution as soon as I can.

2020-10-14 10:50 UTC, peterdmv commented
I'll provide a fix for this issue in #2801. Therefore, I close this PR.
Thank you for your contribution!

2020-10-14 10:50 UTC, closed without merging

2020-10-15 11:23 UTC, robertoaloi commented
Thank you for following up!