Implement NSS-style keylog in ssl:connection_information/2
erlang/otp pull request #2823
Opened 2020-10-23 18:18 UTC by dotsimon

This commit provides the ability to retreive keylog information that
can be used by tools (e.g. Wireshark) to decrypt TLS connections.

The information returned by the keylog connection_information item is
a list of keylog items that can be written to a file or otherwise
communicated to a tool understanding keylog.

For example:
```
{ok, [{keylog, KeylogItems}]} = ssl:connection_information(S, [keylog]).
file:write_file("/tmp/key.log", [[KeylogItem,$\n] || KeylogItem <-KeylogItems]).
```

For TLSv1.3 connections more information must be stored in the connection state. In this case the initial `ssl:listen` or `ssl:connect` call must include the option `{keylog, true}`

For TLSv1.2 connections, the required information could be obtained from the existing `master_secret` and `client_random` items and the keylog item constructed manually. However this PR provides a common method regardless of the protocol.

References:
[NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format)
[Wireshark](https://wiki.wireshark.org/TLS#Using_the_.28Pre.29-Master-Secret)

2020-11-02 15:33 UTC, peterdmv requested changes
Looks good, I have just a few comments to the documentation.

2020-11-02 15:33 UTC, peterdmv commented on lib/ssl/doc/src/ssl.xml
> +      <name name="keep_secrets" since="OTP 23.1"/>
```since``` tags only work with functions. It would be better to document it in the description: "Since OTP 23.2."

2020-11-02 21:21 UTC, dotsimon commented
> Looks good, I have just a few comments to the documentation.

Should be all fixed now. Thanks for the review.

2020-11-03 07:47 UTC, peterdmv approved these changes

2020-11-09 13:44 UTC, merged

2020-11-09 13:45 UTC, peterdmv commented
Thank you for your contribution!