Fix negative zero to string
erlang/otp pull request #2903
Opened 2020-12-02 15:07 UTC by josevalim

Both float_to_binary and float_to_list will correctly
print negative zeros when using the scientific mode but
not when using the decimal representation. This patch
makes it consistent to always show negative floats.

This is important because some operations, such as math:atan2,
will return drastically different results if negative zeros
are given compared to positive zeros. Negative zeros also
are encoded differently in bitstrings.

2020-12-02 16:45 UTC, josevalim commented
PR updated to also fix io:format.

2020-12-07 12:10 UTC, bjorng requested changes

2020-12-07 12:10 UTC, bjorng commented on erts/emulator/test/num_bif_SUITE.erl
> +    <<"-0.0e+00">> = erlang:float_to_binary(NegZero, [{scientific, 1}, compact]),
You don't need the `erlang:` prefix.

2020-12-07 19:46 UTC, josevalim commented on erts/emulator/test/num_bif_SUITE.erl
> +    <<"-0.0e+00">> = erlang:float_to_binary(NegZero, [{scientific, 1}, compact]),
Fixed.

2020-12-08 05:03 UTC, bjorng approved these changes

2020-12-08 05:04 UTC, bjorng commented
Added to our daily builds.

2020-12-11 08:09 UTC, merged