erl_gc: fix dynamic tracepoint for heap_grow
erlang/otp pull request #2932
Opened 2020-12-15 19:21 UTC by max-au

If stack top is changed before calling heap_grow tracepoint,
the stack is not walk-able, because stack bottom points to
old heap, while stack top is already reset to new heap.

2020-12-16 10:48 UTC, garazdawi commented
Wouldn't it make more sense to let the probe trigger after all the pointers have been updated to the new heap? That way the heap is also valid to traverse if one wants to.

Since we cannot write a testcase for this (I assume?), please add a comment in the code about why that line has to be after/before the dtrace probe.

2020-12-17 01:12 UTC, max-au commented
If I understand correctly, old and new heaps are expected to be identical. 

I can change it either way (e.g. move DTRACE invocation after HEAP_END(p) = n_heap + new_sz; or move it before     /* Copy stack to end of new heap */, or add a comment). What would be the preferred solution?

2020-12-17 07:32 UTC, garazdawi commented
> If I understand correctly, old and new heaps are expected to be identical.

Yes, but by the time the GC is done the previous heap will have been destroyed by GC forward pointers so it cannot be read, while the new heap will be intact.

> I can change it either way (e.g. move DTRACE invocation after HEAP_END(p) = n_heap + new_sz; or move it before /* Copy stack to end of new heap */, or add a comment). What would be the preferred solution?

I think it would be best to move the DTRACE call until after all of the heap pointers have been updated.

2020-12-18 10:27 UTC, garazdawi requested changes

2020-12-18 10:27 UTC, garazdawi commented on erts/emulator/beam/erl_gc.c
> +    if (HEAP_SIZE(p) != new_sz && DTRACE_ENABLED(process_heap_grow)) {
`HEAP_SIZE(p) != new_sz` will always be false here.

2020-12-18 10:27 UTC, garazdawi commented on erts/emulator/beam/erl_gc.c
> +    if (HEAP_SIZE(p) != new_sz && DTRACE_ENABLED(process_heap_grow)) {
`HEAP_SIZE(p) != new_sz` will always be false here.

2020-12-22 07:43 UTC, merged