Fix typos in lib/debugger
erlang/otp pull request #5497
Opened 2021-12-07 22:26 UTC by kianmeng

2021-12-08 09:07 UTC, bjorng requested changes

2021-12-08 09:07 UTC, bjorng commented on lib/debugger/test/int_SUITE_data/my_lists.erl
> +%% flat_length(List) (undocumented can be remove later)
```suggestion
%% flat_length(List) (undocumented can be removed later)
```

2021-12-08 09:07 UTC, bjorng commented on lib/debugger/test/int_SUITE_data/my_lists.erl
> +%% flat_length(List) (undocumented can be remove later)
```suggestion
%% flat_length(List) (undocumented can be removed later)
```

2021-12-08 09:07 UTC, bjorng commented on lib/debugger/test/int_SUITE_data/lists1.erl
> +%% flat_length(List) (undocumented can be remove later)
```suggestion
%% flat_length(List) (undocumented can be removed later)
```

2021-12-08 09:07 UTC, bjorng commented on lib/debugger/test/int_SUITE_data/my_lists.erl
> +%% flat_length_2(List) _2(undocumented can be remove later)
```suggestion
%% flat_length_2(List) _2(undocumented can be removed later)
```

2021-12-08 09:07 UTC, bjorng commented on lib/debugger/test/int_SUITE_data/my_lists.erl
> +%% flat_length_3(List) _3(undocumented can be remove later)
```suggestion
%% flat_length_3(List) _3(undocumented can be removed later)
```

2021-12-08 09:07 UTC, bjorng commented on lib/debugger/test/int_eval_SUITE.erl
> +%% Try evaluate spawn_link/3.
```suggestion
%% Try evaluating spawn_link/3.
```

2021-12-08 22:41 UTC, kianmeng commented
@bjorng Done, and commits squashed.

2021-12-09 03:40 UTC, bjorng requested changes
Thanks. I found one more "remove" that should be changed to "removed" that I missed last time I reviewed.

2021-12-09 03:40 UTC, bjorng commented on lib/debugger/test/dbg_ui_SUITE_data/manual_data/src/lists1.erl
> +%% flat_length(List) (undocumented can be remove later)
```suggestion
%% flat_length(List) (undocumented can be removed later)
```

2021-12-10 03:43 UTC, bjorng approved these changes

2021-12-10 03:56 UTC, merged

2021-12-10 03:57 UTC, bjorng commented
Thanks!