Fix typos in lib/ssh
erlang/otp pull request #5564
Opened 2021-12-31 08:03 UTC by kianmeng

2022-01-18 10:00 UTC, lisztspace requested changes
Thanks for your excellent corrections to quite a few typos in code and documentation.  Theer are, however, a few that actually are not typos and should remain.  Please see comments.

2022-01-18 10:00 UTC, lisztspace commented on lib/ssh/src/ssh_xfer.erl
> -	  (creat) -> ?SSH_FXF_CREAT;
Not a typo, but naming inherited from Ye Olde Standards.

2022-01-18 10:00 UTC, lisztspace commented on lib/ssh/src/ssh_xfer.erl
> -		 {?SSH_FXF_CREAT, creat},
Not a typo, but naming inherited from Ye Olde Standards.

2022-01-18 10:00 UTC, lisztspace commented on lib/ssh/src/ssh_sftpd.erl
> -sftp_to_erlang_flag(creat, Vsn) when Vsn == 3;
Not a typos, but naming inherited from Ye Olde Standards.

2022-01-18 10:00 UTC, lisztspace commented on lib/ssh/src/ssh_sftp.erl
> -		 [write, creat, trunc];
Not a typo, but naming inherited from Ye Olde Standards.

2022-01-19 06:08 UTC, lisztspace requested changes

2022-01-19 06:08 UTC, lisztspace commented on lib/ssh/test/ssh_sftp_SUITE.erl
> -    ok = open_close_file(Sftp, SftpFileName, [write, creat]),
Not a typo.  Name inherited from old standards.

2022-01-19 06:08 UTC, lisztspace commented on lib/ssh/test/ssh_relay.erl
> +    %% So annoying there is no select-like semantics for this
Changed to "semantics" as "semantic" is adjective.

2022-01-20 06:56 UTC, lisztspace reviewed
Thanks for the update.  This has now been added for internal testing.

2022-02-02 06:11 UTC, merged

2022-02-02 06:11 UTC, lisztspace commented
Thank you for your contribution to increasing readability.

2022-02-02 08:33 UTC, kianmeng commented
:tada: :tada: :tada: :tada: :tada: