erts|stdlib: Fix io:puts_char error with invalid binary
erlang/otp pull request #5885
Opened 2022-04-13 04:05 UTC by maennchen

Makes sure that io:puts_char/2 emits a no_translation error
when called with an incomplete binary and adds detail to the
resulting error message.

Follow up of https://groups.google.com/g/elixir-lang-core/c/RR7nbeHsluQ  
Related to https://github.com/elixir-lang/elixir/pull/11756

Since this slightly changes the behavior of the function (although in a way that I think is intended), I opened the PR for the `master` branch and not for `maint`. If that is a miscalculation, I'll rebase this onto `maint`.

This is my first PR to OTP and I tried to follow all guidelines. If something is not up to the usual standards, please let me know :)

2022-04-13 04:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/erlang/otp?pullRequest=5885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/erlang/otp?pullRequest=5885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/erlang/otp?pullRequest=5885) it.</sub>

2022-04-13 10:05 UTC, maennchen commented
I believe that failure is not caused by my changes. Is there any way to re-run the CI job?

2022-04-13 11:27 UTC, garazdawi commented
> I believe that failure is not caused by my changes. Is there any way to re-run the CI job?

It is an unstable test case that tends to fail. All other tests pass so your fix seems ok.

2022-04-19 06:22 UTC, garazdawi requested changes
Hello! The tests run fine and I was just about to merge this when I noticed a small copy-paste error in the test code. Would you mind fixing that? and I'll merge when that is done.

2022-04-19 06:22 UTC, garazdawi commented on lib/stdlib/test/io_SUITE.erl
> +    Unicode1Dev = fun() ->
```suggestion
    UnicodeDev = fun() ->
```

2022-04-19 06:22 UTC, garazdawi commented on lib/stdlib/test/io_SUITE.erl
> +         {put_chars,[Unicode1Dev(), <<222>>], [{1,"transcode"}]},
```suggestion
         {put_chars,[UnicodeDev(), <<222>>], [{1,"transcode"}]},
```

2022-04-25 03:41 UTC, maennchen commented
@garazdawi I fixed the names :)

2022-04-25 08:08 UTC, merged

2022-04-25 08:08 UTC, garazdawi commented
thanks!