ssl: Fix version mismatch
erlang/otp pull request #5919
Opened 2022-04-21 12:43 UTC by IngelaAndin

The special case handled by the tls_gen_connection:effective_version
function is only valid in the hello and wait_sh state.

Closes #5835

2022-04-25 15:13 UTC, KennethL requested changes

2022-04-26 06:51 UTC, IngelaAndin commented on lib/ssl/src/tls_gen_connection.erl
> +%% When the negotiated_version variable is not yet set use the highest supported version.
```suggestion
%% When the `negotiated_version` variable is not yet set use the highest supported version.
```

2022-04-26 06:52 UTC, IngelaAndin commented on lib/ssl/src/tls_gen_connection.erl
> +%% In all other cases use version saved in the connection state variable negotiated_version
```suggestion
%% In all other cases use the version saved in the connection state variable `negotiated_version`
```

2022-04-26 06:56 UTC, IngelaAndin commented on lib/ssl/src/tls_gen_connection.erl
> +%% the "initial requested version" kept in the connection state variable negotiated_version
```suggestion
%% the "initial requested version" kept in the connection state variable `negotiated_version`
```

2022-04-26 08:13 UTC, merged