erts: Apply -fno-omit-frame-pointer to erts/lib_src when JIT is enabled
erlang/otp pull request #6048
Opened 2022-06-03 19:25 UTC by d1jang

Currently OMIT_OMIT_FP is set to true in erts/emulator/Makefile.in
when JIT is enabled, but not necessarily in erts/lib_src/Makefile.in.

This change factors out OMIT_OMIT_FP computation to be shared between
those two builds to apply this flag consistently to them.

Note that this bug was confirmed by @garazdawi in an Erlang forum post: https://erlangforums.com/t/unify-builds-for-otp-erts-targets/1419/3

2022-06-03 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/erlang/otp?pullRequest=6048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/erlang/otp?pullRequest=6048) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/erlang/otp?pullRequest=6048) it.</sub>

2022-06-07 06:41 UTC, garazdawi commented
Hello! Thanks for the PR! Would you mind signing the CLA?

2022-06-10 06:38 UTC, garazdawi requested changes
You need to also change [erts/configure.ac](https://github.com/erlang/otp/blob/master/erts/configure.ac#L3598) to include flavor.mk.in as [erts/configure](https://github.com/erlang/otp/blob/master/erts/configure) is a generated file.

2022-06-23 03:57 UTC, d1jang commented
> You need to also change [erts/configure.ac](https://github.com/erlang/otp/blob/master/erts/configure.ac#L3598) to include flavor.mk.in as [erts/configure](https://github.com/erlang/otp/blob/master/erts/configure) is a generated file.

Thanks for the comment! I included the requested change in [erts/configure.ac].

2022-07-12 17:58 UTC, d1jang commented
@garazdawi I made the requested change. Can I ask for a quick review? Thanks!

2022-08-26 13:24 UTC, garazdawi commented
Hello again! The changes in this PR break the building of a non-jit emulator. To reproduce run:

```
./otp_build setup -a
make FLAVOR=emu
```

2022-10-04 12:28 UTC, garazdawi commented
I've pushed changes to your branch to fix the issues and add CI in order to check that the different types and flavors works.

2022-10-05 06:45 UTC, garazdawi approved these changes

2022-10-05 06:49 UTC, merged