Allow the timezone part of the string to contain only an hour
erlang/otp pull request #6108
Opened 2022-06-25 09:35 UTC by dischoen

RFC3339 declares the minutes part of the timezone diff as optional,
which is now enabled with this commit.
E.g.: 2022-06-25 11:04:00+02 is now possible.

2022-06-28 11:17 UTC, bjorng requested changes
Thanks for your pull request.

I've change the target of the pull request to maint so that it can be included in OTP 25.1.

I have suggested one simplification of the code in a comment. Also, I would want you to add a note the documentation that starting from OTP 25.1, the minutes part of the timezone diff is now optional.

2022-06-28 11:17 UTC, bjorng commented on lib/stdlib/src/calendar.erl
> +offset_string_adjustment(_Time, _Unit, Tz) when length(Tz) == 6 ->
```suggestion
offset_string_adjustment(_Time, _Unit, Tz) ->
    [Sign, H1, H2 | MinutesDiff] = Tz,
    Hour = list_to_integer([H1, H2]),
    Min = case MinutesDiff of
              [$:, M1, M2] ->
                  list_to_integer([M1, M2]);
              [] ->
                  0
          end,
    Adjustment = 3600 * Hour + 60 * Min,
    case Sign of
        $- -> -Adjustment;
        $+ -> Adjustment
    end.
```

(and also remove the rest of the function after your changes)

2022-06-28 11:46 UTC, dischoen commented
@bjorng I have accepted your suggestion (hope I did it right, I don't have much experience with pull requests on github).
I will do the documentation change tonight.

2022-06-29 08:35 UTC, bjorng approved these changes

2022-07-01 02:33 UTC, merged

2022-07-01 02:33 UTC, bjorng commented
Thanks for your pull request.