Regular expression replacement with a function
erlang/otp pull request #6197
Opened 2022-08-04 11:54 UTC by juhlig

I rarely use regular expressions with Erlang. But when I do, I often would need a function to process matches and create replacements.

This PR extends `re:replace/3,4` to accept a 2-ary function for the replacement. This function will be called with the entire match as the first and a list of subexpression matches as second argument. The value returned from the function will be inserted into the result.

A problem exists in case of regular expressions like this:
```
".(x)?(y)?"
```
When applied to a string like `"axy"`, the function will be called with arguments `<<"ax">>` and `[<<"x">>, <<"y">>]`.
When applied to `"ax"`, the arguments will be `<<"ax">>` and `[<<"x">>]`, ie the subexpression match list _does not_ contain the optional-ish match related to `(y)`.
When applied to `"ay"`, the arguments will be `<<"ay">>` and `[<<>>, <<"y">>]`, ie the subexpression match list _does_ contain the optional-ish match related to `(x)` as an empty binary.

I'm not sure how to handle this (and that is why it is not documented yet). The implementation for replacements using strings with back references inserts empty binaries if the match index does not exist in the actual match. For creating the subexpression match list for replacement via a function however, something like this is not possible. The easiest way out may be to recommend a catch-all clause that will return an empty binary, in the documentation.

2022-08-23 06:50 UTC, bjorng requested changes
Looks good to me. I think that we should handle optional capturing patterns as you suggested, namely documenting the behavior and leave it up to the user's fun to handle it. In practice, I wouldn't expect such patterns to be very common, so most replacement funs wouldn't have to handle it.

Please add more details to the commit message, so that if anyone wonders what happened 10 years from now don't have to locate the pull request, but can find the details in the commit message.

2022-08-23 13:53 UTC, juhlig commented
Ok, great :) I applied your suggestions and will finish up the docs, squash the commits and write a more elaborate commit message tomorrow.

2022-08-24 09:35 UTC, juhlig commented
@bjorng I documented the short subexpression list behavior as best as I could, what do you think? I also augmented the commit message as requested.

2022-08-24 11:04 UTC, bjorng approved these changes
Looks good. Added to our daily builds.

2022-08-24 12:08 UTC, juhlig commented
There is some strange failure in the doc build, that seems to be unrelated to my changes :man_shrugging:

2022-08-24 12:22 UTC, bjorng commented
> There is some strange failure in the doc build, that seems to be unrelated to my changes.

Yes, it is unrelated to your changes.

2022-08-26 05:36 UTC, merged

2022-08-26 05:37 UTC, bjorng commented
Thanks for your pull request.