[erts] Display large maps similarly to small maps
erlang/otp pull request #6497
Opened 2022-11-22 22:39 UTC by lmth

The formatting of large maps done by erlang:display/1 used to reveal interesting information about the map internals, but was difficult to read, compared to the formatting of small maps. This commit aims at a similar (but still not sorted) display of large maps as for small maps.

This is important to those of us who regularly try to understand the state of our system from erlang:process_info(...,backtrace) or erlang:system_info(procs).

Pull request submitted based on issue #5585 discussion.

2022-11-22 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/erlang/otp?pullRequest=6497) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/erlang/otp?pullRequest=6497) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/erlang/otp?pullRequest=6497) it.</sub>

2022-12-08 08:21 UTC, bjorng requested changes
Thanks for you pull request.

Your implementation of map printing looks good.

However, I think that the test case should be more challenging, testing nested maps, and that the maps are printed correctly. Therefore, I've updated the test case and pushed it to your branch. I've also made sure that indentation in the C code is done using spaces instead of tabs.

If you agree to those changes, please squash all four commits down to a single commit.

Also, since this is not a bug fix, I think we should not release it in a maintenance release. Please rebase the branch on `master` and retarget the pull request to `master`.

2022-12-08 12:57 UTC, lmth commented
Hi, @bjorng !

I obviously like the improvements you made to the branch, and have squashed and rebased.

/Magnus T

2022-12-08 13:13 UTC, bjorng commented
Thanks! Added to our daily builds.

2022-12-08 13:14 UTC, bjorng approved these changes

2022-12-09 13:11 UTC, bjorng commented
My suggested test case failed on runtime system using the old non-JIT BEAM emulator because of subtle differences in how the stack is managed.

I turns out that there is much easier way to get back what `erlang:display/1` would print. It's an undocumented function called `erts_debug:display/1`. I have updated test case and force-pushed.

2022-12-09 16:11 UTC, lmth commented
Hi @bjorng,

I see - I was looking for some way of capturing the output of display but failed and thought I had to resort to a process stack dump of some sort. This is more to-the-point.

Do I have to do anything?

/Magnus T

2022-12-11 08:34 UTC, bjorng commented
@lmth You don't have to do anything.

2022-12-13 11:45 UTC, merged

2022-12-13 11:45 UTC, bjorng commented
Thanks!