Fix bug introduced in PR 6359
erlang/otp pull request #6527
Opened 2022-12-01 22:59 UTC by RobinMorisset

In https://github.com/erlang/otp/pull/6359, I used the new ets:lookup_element/4 in various places in the standard library.

In particular, I replaced a try/catch wrapping a call to lookup_element/3 in 3 places. Unfortunately, this catch was also catching the case where the table does not exist at all, and this breaks some applications.

This patch just restores the 3 try/catches.

2022-12-02 06:06 UTC, bjorng requested changes

2022-12-02 06:06 UTC, bjorng commented on lib/kernel/src/pg.erl
> +        % Case where the table does not exist yet.
```suggestion
        %% Case where the table does not exist yet.
```

2022-12-02 10:29 UTC, bjorng approved these changes
Thanks! Please squash your commits.

2022-12-05 11:29 UTC, RobinMorisset commented
Thanks for the review, I just squashed them.

2022-12-05 12:25 UTC, bjorng commented
Thanks! Added to our daily builds.

2022-12-06 14:14 UTC, merged