crypto: replace size/1 by byte_size/1
erlang/otp pull request #6768
Opened 2023-02-01 13:53 UTC by kikofernandez

The <c>size/1</c> BIF is not optimized by the JIT, and its use can result in worse types for Dialyzer.

When one knows that the value being tested must be a tuple, <c>tuple_size/1</c> should always be preferred.

When one knows that the value being tested must be a binary, <c>byte_size/1</c> should be preferred.

Links to #6672

2023-02-02 06:07 UTC, bjorng requested changes

2023-02-02 06:07 UTC, bjorng commented on lib/crypto/src/crypto.erl
>          N -> << 0:(N*8), Binary/binary>>
```suggestion
    case srp_pad_length(Width, bit_size(Binary)) of
        0 -> Binary;
        N -> << 0:N, Binary/binary>>
```

2023-02-02 10:59 UTC, bjorng approved these changes

2023-02-03 13:40 UTC, kikofernandez commented
All tests pass locally, so I merge

2023-02-03 13:41 UTC, merged