Implement simple command-line serving via httpd
erlang/otp pull request #7299
Opened 2023-05-25 10:11 UTC by jchristgit

Often times people want to quickly have a directory index of some folder to either view directly or share on the local network. For instance, in Python, `python3 -m http.server` implements a simple server accomplishing exactly this.

`httpd` has the needed functionality to do this, but did not define a command-line entrypoint. Users who wanted to quickly serve files with Erlang needed hacks like shown here:
https://gist.github.com/willurd/5720255#erlang. This commit adds support for the following forms of hosting a simple directory listing with support for `index.html` and basic mimetypes, with the following commands:

    erl -s httpd
    erl -s httpd serve
    erl -s httpd serve path/to/dir

Instead of `-s`, `-run` is also supported. The original suggestion cropped up here:
https://erlangforums.com/t/httpc-httpd-improvements/2622/8

**This is just a suggestion**: feel free to reject it. If the team wants to add these changes, I can refine this as needed.

2023-06-07 13:03 UTC, jchristgit commented
Thanks for the feedback.

I've pushed a more complete implementation together with docs, tests, and the two command-line options `--bind` and `--port`, parsed via `argparse`.

I also have a rough draft of CGI support stashed away here, but I think that's better for a separate PR.

Argument passing is a bit strange because it requires to parse `-extra` to properly register the additional arguments, perhaps here init can be improved to have a flag like `-S` which internally would work like a combination of `-s` and `-extra` to allow forms such as `erl -S httpd serve --port 4000` directly? I might open a separate issue for this.

As for the test failure, I've noticed that `mod_alias` uses the configured `server_name` when performing redirects instead of the URL of the client, which breaks when the server name is not a hostname under which the server is reachable. Is there a reason this doesn't use the absolute request URL on the rewrite, maybe security? I believe it would also be possible to just redirect to a path and have the browser figure it out. But perhaps we should skip / xfail the test here for now?

2023-06-19 13:12 UTC, jchristgit commented
I pushed some small changes in my latest update to the commit:

- instead of serving in wherever the test server runs, serve in the data directory of the suite (added as well)
- when the server instructs us to redirect, use the connect address we figured out on our own instead of the server-provided one: the server-provided one depends on `server_name` which may not be the reachable address
- run the default port tests with `sequence` such that if one fails the others won't run and clutter logs
- actually retrieve random file to test in the `random_file` assertion instead of picking the first one we find
- regard `eaddrnotavail` as a skip (e.g. IPv6 not available), fail on other server startup errors

Hope this fixes CI - if not I'll work at it 🙂

2023-06-21 11:48 UTC, jchristgit commented
@u3s the tests are more tolerant of unexpected network configurations now, and pass in CI. Let me know if you have something else I should update :slightly_smiling_face:

2023-07-04 09:51 UTC, jchristgit commented
I made a draft PR at https://github.com/erlang/otp/pull/7470 that would ease starting this up, e.g. `erl -S httpd serve --flags` instead of `erl -s httpd serve -extra --flags`. Would be happy for your feedback there.

2023-08-14 08:43 UTC, u3s commented
I'm sorry for delay. We will get back to this one when possible.

2023-08-17 14:14 UTC, u3s commented on lib/inets/test/httpd_serve_SUITE.erl
> +%%   Started HTTP server on 127.0.0.1:8000 at /path/to/lib/inets/make_test_dir/ct_logs/ct_run.test_server@zulu.2023-06-06_12.07.27\n"
Output in my env looks like `127.0.0.1 port 8000`. is the comment actual?

2023-08-17 14:14 UTC, u3s commented on lib/inets/test/httpd_serve_SUITE.erl
> +    run_with_server(TestFun, ServerFun).
maybe I'm missing some convention, but I don't see point in change arguments order between `with_server` and `run_with_server`. wouldn't it be simpler is both functions take ServerFun as 1st and TestFun as 2nd argument?

2023-08-22 13:39 UTC, u3s commented
for reference, this PR potentially depends on #7470 (which I guess should be merged first)

2023-09-01 07:53 UTC, u3s commented
- are some adjustments needed to make `erl -S httpd serve` work properly?
- maybe also update docs to cover `-S` (do you think it would be enough if documentation only covers `-S` ?)
- please squash commits

2023-09-01 11:48 UTC, u3s commented
>> - maybe also update docs to cover `-S` (do you think it would be enough if documentation only covers `-S` ?)

> Actually I think it may be cleaner to both only document & only support `-S` because it will prevent any surprises with option parsing. What do you think?

I agree, I think this is inline with `simple` from the PR title and will reduce confusion.

2023-09-06 09:59 UTC, u3s requested changes
- please fix error message (--exrta is no longer worth mentioning)
- I might have found some issue with `-S` which affects this PR (see comment in #7470 )

2023-09-06 09:59 UTC, u3s commented on lib/inets/src/http_server/httpd.erl
> +        "must be passed after the `-extra` flag of the emulator."
`-extra` is not relevant any longer?

2023-09-06 15:26 UTC, u3s approved these changes

2023-09-13 08:19 UTC, merged