ssl: Add UG entry about signatue algorithm configuration
erlang/otp pull request #7372
Opened 2023-06-07 10:31 UTC by IngelaAndin

User guide addition about signature algorithms

2023-06-07 10:56 UTC, KennethL requested changes

2023-06-07 10:56 UTC, KennethL commented on lib/ssl/doc/src/using_ssl.xml
> +    default signature_algorithm list in OTP-26 and cryptolib form
form -> from

2023-06-07 10:56 UTC, KennethL commented on lib/ssl/doc/src/using_ssl.xml
> +    configuration is in prefered order. See also  <seemfa
```suggestion
    configuration is in prefered order. like this:</p>
    <code>
    MySignatureAlgs = ssl:signature_algs(default, 'tlsv1.3') ++ [rsa_pkcs1_sha512, rsa_pkcs1_sha384],
    ssl:connect(Ip,Port,[{signature_algs, MySignatureAlgs,...]}),
    ...
    </code>
    <p>See also  <seemfa
```

2023-06-07 11:11 UTC, IngelaAndin commented on lib/ssl/doc/src/using_ssl.xml
> +    default signature_algorithm list in OTP-26 and cryptolib form
Good catch, fixed

2023-06-09 09:05 UTC, u3s approved these changes

2023-06-09 09:05 UTC, u3s commented on lib/ssl/doc/src/using_ssl.xml
> +    TLS-1.2 and can be used aslo in a TLS-1.2 configuration. Also note
Not an expert on grammar, but shouldn't you put a coma (`,`) after "Also note" ?

2023-06-09 09:05 UTC, u3s commented on lib/ssl/doc/src/using_ssl.xml
> +    for your system. For example if TLS-1.3 and TLS-1.2 is supported the
coma after "For example" ?

2023-06-09 09:05 UTC, u3s commented on lib/ssl/doc/src/using_ssl.xml
> +    configuration is in prefered order, like this:</p>
typo: prefered -> preferred?

2023-06-09 09:17 UTC, IngelaAndin commented on lib/ssl/doc/src/using_ssl.xml
> +    configuration is two tuples composed by one hash algorithm and one
Yes that is what I mean, I guess leaving element out is a bit sloppy and would actually not have the intended meaning! I will add element to the sentence!

2023-06-09 09:18 UTC, IngelaAndin commented on lib/ssl/doc/src/using_ssl.xml
> +    TLS-1.2 and can be used aslo in a TLS-1.2 configuration. Also note
fixed

2023-06-09 09:26 UTC, IngelaAndin commented on lib/ssl/doc/src/using_ssl.xml
> +    for your system. For example if TLS-1.3 and TLS-1.2 is supported the
Reformulated a bit!

2023-06-09 09:28 UTC, IngelaAndin commented on lib/ssl/doc/src/using_ssl.xml
> +    configuration is in prefered order, like this:</p>
fixed

2023-06-14 14:35 UTC, dgud approved these changes

2023-06-15 07:25 UTC, merged