public_key: pubkey_policy_tree_SUITE and tree visualization
erlang/otp pull request #7814
Opened 2023-11-02 09:20 UTC by u3s

2023-11-03 20:11 UTC, IngelaAndin requested changes

2023-11-03 20:11 UTC, IngelaAndin commented on lib/public_key/test/pubkey_policy_tree_SUITE.erl
> +        end,
Would it not be more interesting to have a tree where the second function is applied to more than one parent and hence fun1 and fun2 actually can have different outcomes?

2023-11-07 11:58 UTC, u3s commented on lib/public_key/test/pubkey_policy_tree_SUITE.erl
> +-define(ANY_POLICY_OID, {2,5,29,32,0}).
fixed

2023-11-07 11:58 UTC, u3s commented on lib/public_key/test/pubkey_policy_tree_SUITE.erl
> +    TreeWithAnyPolicyNode1 = {?ROOT_PN,
fixed

2023-11-08 15:20 UTC, IngelaAndin approved these changes

2023-11-08 17:37 UTC, merged