Paging in shell for autocompletion and search
erlang/otp pull request #7845
Opened 2023-11-09 11:50 UTC by frazze-jobb

Adds scrollable pager for large outputs for shell hotkeys.

2023-11-09 12:01 UTC, dgud commented
I'm old school and don't want paging, can an option (or function) be added to turn off all paging?

2023-11-09 12:19 UTC, garazdawi commented
Tests and docs?

2023-11-14 10:03 UTC, garazdawi requested changes
Neat! Some tests and this should be good to go.

2023-11-15 11:49 UTC, frazze-jobb commented
> I'm old school and don't want paging, can an option (or function) be added to turn off all paging?

I'll do that in a separate PR, you can already disable paging for expand, but for c:h/* and c:i/* I wanted to try to make it use the new paging mechanism, but I didn't figure out how I could do that without deadlocking so I need to think some more.

2023-11-15 11:49 UTC, frazze-jobb commented on lib/kernel/src/prim_tty.erl
> +                                true -> StatusLine = io_lib:format("\e[37;46mrows ~w to ~w of ~w\e[0m", [ERow, ERow + R-1-InputRows, ExpandRows]),
I made a function instead

2023-11-23 11:31 UTC, garazdawi requested changes
If I type: `s` `<TAB>` `<END>` then any up/down/pageup/pagedown i type is ignored. Seems like maybe pressing `<END>`  should trigger autocompletion to be cancelled? When I precc `<HOME>` it is cancelled.

2023-11-23 11:31 UTC, garazdawi commented on lib/kernel/src/prim_tty.erl
> +                            BufferExpandLines = string:split(erlang:binary_to_list(BufferExpand), "\n", all),
```suggestion
                            BufferExpandLines = string:split(unicode:characters_to_list(BufferExpand), "\n", all),
```

2023-11-23 11:31 UTC, garazdawi commented on lib/kernel/src/prim_tty.erl
> +                          {ExpandBuffer, NewState} = insert_buf(RedrawState#state{ buffer_expand = [] }, iolist_to_binary(BufferExpand1)),
```suggestion
                          {ExpandBuffer, NewState} = insert_buf(RedrawState#state{ buffer_expand = [] }, unicode:characters_to_binary(BufferExpand1)),
```

2023-11-23 11:31 UTC, garazdawi commented on lib/kernel/src/prim_tty.erl
> +                            BufferExpand1 = case ExpandRows > (R-InputRows) of
```suggestion
                            BufferExpand1 = case ExpandRows > ExpandRowsLimit1 of
```

2023-11-23 11:31 UTC, garazdawi commented on lib/kernel/src/prim_tty.erl
> +    ERow1 = if ExpandRows > WindowRows-InputRows -> %% We need to page expand rows
Something is off with this calculation. When the number of rows is less than windows size but larger than 7 the navigation does not work.

To see the effect type `l` `<TAB>`  and then try to navigate.

2023-12-12 11:04 UTC, frazze-jobb commented on lib/stdlib/src/edlin.erl
> +                    edit(Buf, P, MultiLine, {normal,none}, [{move_rel, 0}|Rs0]);
@garazdawi: End will now close the expand, because of this added {move_rel, 0} event.

2023-12-12 11:11 UTC, merged