stdlib: add auto formatting to the shell
erlang/otp pull request #7847
Opened 2023-11-09 12:02 UTC by frazze-jobb

2023-11-13 09:25 UTC, frazze-jobb commented
Will add an additional case to allow a {Module,Function} tuple that takes a string, in case you want to provide an erlang based formatter

2023-11-14 10:14 UTC, garazdawi requested changes
Looks good. Polish tests and docs a bit and this is good to go.

2023-11-14 10:14 UTC, garazdawi commented on lib/kernel/test/interactive_shell_SUITE.erl
> +shell_format(Config) ->
Add a testcase when an external tool is used to format?

2023-11-14 10:14 UTC, garazdawi commented on lib/stdlib/doc/src/stdlib_app.xml
> +        -stdlib shell_formatting "\"emacs -batch \${file} -l ~/erlang-format/emacs-format-file -f emacs-format-function\""
```suggestion
        <code>erl -stdlib shell_formatting "\"emacs -batch \${file} -l ~/erlang-format/emacs-format-file -f emacs-format-function\""</code>
```

2023-11-14 10:14 UTC, garazdawi commented on lib/stdlib/doc/src/stdlib_app.xml
> +      <item>
Add a cross link to `shell:shell_format_func/1` somewhere in these docs.

And also, should this config variable not be named the same as the function?

2023-11-14 10:14 UTC, garazdawi commented on lib/stdlib/doc/src/shell.xml
> +      <name name="format_shell_func" arity="1" since="OTP @OTP-18848@"/>
Add a cross-link to `stdlib_app#format_shell_command` somewhere in these docs.

2023-11-14 10:14 UTC, garazdawi commented on lib/stdlib/doc/src/shell.xml
> +        shell:format_shell_func("\"emacs -batch \${file} -l ~/erlang-format/emacs-format-file -f emacs-format-function\"").
```suggestion
        <code>shell:format_shell_func("\"emacs -batch \${file} -l ~/erlang-format/emacs-format-file -f emacs-format-function\"").</code>
```

2023-11-23 09:56 UTC, garazdawi commented on lib/stdlib/doc/src/stdlib_app.xml
> +        <p>Can be used to set the formatting of the Erlang shell output. This have an effect
```suggestion
        <p>Can be used to set the formatting of the Erlang shell output. This has an effect
```

2023-11-23 09:56 UTC, garazdawi commented on lib/stdlib/doc/src/stdlib_app.xml
> +        on commands that have been submitted, and how it is saved in history. Or if the
```suggestion
        on commands that have been submitted and how it is saved in history or if the
```

2023-11-23 09:56 UTC, garazdawi commented on lib/stdlib/doc/src/stdlib_app.xml
> +        </p>
Can `erl_pp` be used? If so, maybe add an example?

2023-11-23 09:56 UTC, garazdawi commented on lib/kernel/src/group.erl
> +    catch
If the formatting function crashes, we should log and possibly remove the current formatter?

2023-12-28 20:46 UTC, merged