ssl: Support check should check minimum support
erlang/otp pull request #8504
Opened 2024-05-23 14:52 UTC by IngelaAndin

Will make TLS-1.3 work with fips

2024-05-24 09:32 UTC, u3s requested changes
#9 4.725 tls_record.erl:422:5: syntax error before: lists
#9 4.725 %  422|     lists:all(Fun, L);
#9 4.725 %     |     ^

2024-05-24 11:50 UTC, IngelaAndin commented
@u3s humm forgot to commit last changes should be fixed now.

2024-05-24 13:47 UTC, IngelaAndin commented
There seems to test case issues probably as test wants to check for more than minimal algorithms, will look into it next week.

2024-05-29 12:36 UTC, dgud approved these changes

2024-05-29 12:36 UTC, dgud commented on lib/ssl/src/tls_record.erl
> +   %% Minimum requierment check
```suggestion
   %% Minimum requirement check
```

2024-05-30 10:29 UTC, IngelaAndin commented on lib/ssl/src/tls_record.erl
> +   %% Minimum requierment check
fixed

2024-05-30 10:34 UTC, merged