public_key: Correct match_name function for dnsNames
erlang/otp pull request #8508
Opened 2024-05-24 08:58 UTC by IngelaAndin

Closes #8482

2024-05-24 09:30 UTC, u3s requested changes
pkits_SUITE fails ... ?

2024-05-24 11:12 UTC, IngelaAndin commented
@u3s yes I noticed, problem was a little more intricate then it first seemed.  Should be fixed now!

2024-05-24 13:56 UTC, u3s approved these changes

2024-05-27 05:38 UTC, merged

2024-06-24 06:14 UTC, IngelaAndin commented
Planned for  OTP 26.2.5.1 and OTP-27.0.1, next upcoming patches. Summer period is a little slower due to vacation period. Can not give you any date, but will be announced at the https://erlangforums.com/