Add json format functions for key-value lists
erlang/otp pull request #8889
Opened 2024-10-02 15:06 UTC by isvilen

Support formatting key-value lists while preserve their ordering.
Closes #8882

2024-10-02 15:11 UTC, vkatsuba commented on lib/stdlib/src/json.erl
> +
```suggestion
```

2024-10-02 15:11 UTC, vkatsuba commented on lib/stdlib/src/json.erl
> +
```suggestion
```

2024-10-02 15:11 UTC, vkatsuba commented on lib/stdlib/src/json.erl
> +
```suggestion
```

2024-10-02 15:11 UTC, vkatsuba commented on lib/stdlib/src/json.erl
> +    NextState = State#{level := Level+1},
```suggestion
    NextState = State#{level := Level + 1},
```

2024-10-04 06:43 UTC, Maria-12648430 commented on lib/stdlib/src/json.erl
> +                    _ ->
```suggestion
                    false ->
```
Better be explicit ;)

2024-10-07 12:36 UTC, vkatsuba approved these changes

2024-10-08 13:36 UTC, dgud requested changes

2024-10-25 07:48 UTC, dgud commented
Can you squash the commits and force-push..

2024-10-25 11:39 UTC, isvilen commented
> Can you squash the commits and force-push..

Done, should I also rebase it onto main ?

2024-10-25 12:53 UTC, dgud commented
I think you are already based of *maint* branch. 

I could merge it without getting any changes from master, what I saw at least, but could have missed something.
Checked and it looks ok to me, before the squash at least and still good after squash :-)

2024-10-31 16:18 UTC, merged