ssl: fix test code compilation warnings
erlang/otp pull request #8893
Opened 2024-10-03 09:00 UTC by u3s

2024-10-03 10:14 UTC, dgud commented
Does this fix all warnings? If so why not turn on warnings as errors in the makefile so we don't introduce new ones.

2024-10-03 10:39 UTC, u3s commented
> Does this fix all warnings?
I believe it does.

> If so why not turn on warnings as errors in the makefile so we don't introduce new ones.
I thought about it but didn't dare doing it ;-) @IngelaAndin what do you say about that proposal?

2024-10-04 08:58 UTC, IngelaAndin commented
I do not mind having no warnings if possible, I am all for that. I do know that there exist situations in testing where you want to deliberate do things that will cause warnings in able to provoke some kind of error for negative testing. I have not evaluated if we have such code in ssl tests (maybe not). I think it is unreasonable to require all  test code to be waring free, and if you can solve it by suppressing particular warnings that is good too. I think the argument was that some warnings could not be suppressed. But if you got rid off all warnings why not require it for ssl test for now and if we feel we need to have a warning we can cross that bridge when we get there.

2024-10-04 09:04 UTC, dgud commented
You can always temporary remove that during development.

2024-10-04 09:22 UTC, IngelaAndin commented
> You can always temporary remove that during development.

Sure, this I do not care about, I do not mind fixing the warnings. The problem as I see it is if you want to do a bad-match or something to force something to crash and see how it is handled, at least that  is the argument that is usually made. Maybe there could be some other trick or the particular warning can be suppressed, fine by me.

2024-10-04 12:47 UTC, Maria-12648430 requested changes

2024-10-04 12:47 UTC, Maria-12648430 commented on lib/ssl/test/ssl_renegotiate_SUITE.erl
> +     " to lower treshold substantially."}].
```suggestion
     " to lower threshold substantially."}].
```

2024-10-04 12:47 UTC, Maria-12648430 commented on lib/ssl/test/ssl_renegotiate_SUITE.erl
> +					       trigger_renegotiate, [[ErlData, treshold(N, Version)]]}},
```suggestion
					       trigger_renegotiate, [[ErlData, threshold(N, Version)]]}},
```

2024-10-04 12:47 UTC, Maria-12648430 commented on lib/ssl/test/ssl_renegotiate_SUITE.erl
> +     " to lower treshold substantially."}].
```suggestion
     " to lower threshold substantially."}].
```

2024-10-04 12:47 UTC, Maria-12648430 commented on lib/ssl/test/ssl_renegotiate_SUITE.erl
> +treshold(N, ?TLS_1_0) ->
```suggestion
threshold(N, ?TLS_1_0) ->
```

2024-10-04 12:47 UTC, Maria-12648430 commented on lib/ssl/test/ssl_renegotiate_SUITE.erl
> +treshold(N, _) ->
```suggestion
threshold(N, _) ->
```

2024-10-04 17:11 UTC, u3s commented
Thanks @Maria-12648430 :-)

2024-10-08 11:22 UTC, u3s commented
> Does this fix all warnings? If so why not turn on warnings as errors in the makefile so we don't introduce new ones.

Now we collectively recalled the ct auto_compile feature issue which kind of ignores the compilation result of a test suite and tries to execute no matter how bad the compilation went.

If the related beam file is found (could be result of previous succesful compilation) execution attempt will happen.

Therefore, I would like to merge this PR as is - just fixing the warnings.
And adding "warnings as errors" for test suites in the other internal issue for auto_compile feature. I will try to enable it for ssl and ssh.

2024-10-08 11:51 UTC, merged