Ets and Dets code should not be printing to stdout
erlang/otp pull request #9232
Opened 2024-12-21 19:37 UTC by richcarl

Some quite old code in Ets and Dets would print messages to stdout when repairing tables or when fun2ms failed. There were also some leftover debug macros that ought to be removed.

2025-01-07 11:36 UTC, IngelaAndin commented
I think you should use logger instead of calling legacy error_logger functions.

2025-01-07 11:36 UTC, IngelaAndin requested changes
I think you should use logger instead of calling legacy error_logger functions.

2025-01-07 11:40 UTC, richcarl commented
> I think you should use logger instead of calling legacy error_logger functions.

That would introduce a mix of old error_logger calls and new logger calls. I think it is better to follow the existing code style and then replace all of the calls in a separate update.

2025-01-10 08:08 UTC, richcarl commented
Fair enough, I dropped the macro removal. IMO though, the only place for that sort of code is in the version control history.

2025-01-10 18:55 UTC, IngelaAndin approved these changes

2025-01-13 14:31 UTC, merged